import 'dotenv/config'

export const ENV = {
  MONGO_DB: process.env.MONGO_DB,
  DB_NAME: process.env.DB_NAME,
  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,
  BUILD_MODE: process.env.BUILD_MODE,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,
  BREVO_API_KEY:process.env.BREVO_API_KEY,
  ADMIN_EMAIL_BREVO:process.env.ADMIN_EMAIL_BREVO,
  ADMIN_NAME_BREVO:process.env.ADMIN_NAME_BREVO,
  MAILTRAP_KEY:process.env.MAILTRAP_KEY,

  ACCESS_TOKEN_SECRET_SIGNATURE:process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE:process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET_SIGNATURE:process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE:process.env.REFRESH_TOKEN_LIFE
}